Finished pre-commit hook for settings.gradle.kts

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,76 +1,9 @@
-#!/bin/bash
-#
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-#
-# To enable this hook, rename this file to "pre-commit".
+#!/bin/bash -e
+# The -e flag instructs the script to exit on error.
+# https://www.gnu.org/software/bash/manual/bash.html#Modifying-Shell-Behavior
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=$(git hash-object -t tree /dev/null)
-fi
+wd=$(pwd)
+projectdir=$(git rev-parse --show-toplevel || { >&2 echo "ERROR: Git repository directory not found in $wd"; exit 255; })
 
-# If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --type=bool hooks.allownonascii)
+"$projectdir"/.git/hooks/pre-commit-settings-gradle.py < /dev/tty
 
-# Redirect output to stderr.
-exec 1>&2
-
-# Cross platform projects tend to avoid non-ASCII filenames; prevent
-# them from being added to the repository. We exploit the fact that the
-# printable range starts at the space character and ends with tilde.
-if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test "$(git diff --cached --name-only --diff-filter=A -z "$against" | LC_ALL=C tr -d '[ -~]\0' | wc -c)" != 0
-then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
-
-This can cause problems if you want to work with people on other platforms.
-
-To be portable it is advisable to rename the file.
-
-If you know what you are doing you can disable this check using:
-
-  git config hooks.allownonascii true
-EOF
-	exit 1
-fi
-
-# If there are whitespace errors, print the offending file names and fail.
-#exec git diff-index --check --cached "$against" --
-
-projectdir=$(git rev-parse --show-toplevel)
-projectsettings=$projectdir/settings.gradle.kts
-pluginssettings=$projectdir/build-config-plugins/settings.gradle.kts
-projecttext=$(sed -e '/\/\/build-config-plugins-needle/,$d' "$projectsettings")
-pluginstext=$(sed -e '/\/\/build-config-plugins-needle/,$d' "$pluginssettings")
-savepluginstext=$(sed -n -e '/\/\/build-config-plugins-needle/,$p' "$pluginssettings")
-
-
-if [[ $projecttext != "$pluginstext" ]]; then
-  cat <<\EOF
-Error: The build-config-plugins' settings.gradle.kts
-      should be the same as the project's settings.gradle.kts.
-      You can overwrite the file or cancel the commit.
-
-EOF
-  read -t 5 -r -p "Overwrite the build-config-plugins' settings file? [y/N] (5 seconds to respond) " \
-  overwrite < /dev/tty
-
-  if [[ $overwrite == 'y' || $overwrite == 'Y' ]]; then
-    rm -f "$pluginssettings"
-    echo "$projecttext" | cat >> "$pluginssettings"
-    echo "$savepluginstext" | cat >> "$pluginssettings"
-    git add "$pluginssettings"
-  else
-    exit 1
-  fi
-fi
